### ISSUE TITLE
Provide examples for platform data model

### ISSUE THREAD

**Issue by joasilva** [ATTX-project/graphmanager#1]
Examples should combine data from worflow, provenance, working and dissemination data.
How are different THINGS named? Where does the identifiers come from?

Outcomes:
Documentation
Hand-crafted example documents

**Comment by blankdots** [comment]
Hand-crafted examples available at: https://github.com/ATTX-project/graphmanager/tree/master/example_data

**Comment by blankdots** [comment]
Example data available in https://github.com/ATTX-project/graphmanager/tree/feature-dataModelling
As a result of the discussion in solving this taks the identifies, would come from the ETL plugin (to be developed) which will register metadata.
Documentation will be provided along side the ontology data model for the project.

When reviewed merge to dev branch

**Comment by blankdots** [comment]
feature branch merged to dev and deleted
