### ISSUE TITLE
Add license data to datasets

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/graphmanager#16]
#### Description
Every dataset in the platform must have some kind of licensing information attached to it. 
TODO:
- [x] initial vocabulary/model for licensing data
- [x] changes to the platform's data model
- changes to ATTX components
  - [x] WF API
  - [x] new WF API tests
  - [x] ATTX Transformer

#### DoD
First version of documentation and implementation of license information handling in ATTX platform.

#### Testing
Tests for licensing information when creating new datasets.

**Comment by blankdots** [comment]
Reused the CC ontology for license property and class ... https://creativecommons.org/ns#
Current licenses URLs:
* http://data.hulib.helsinki.fi/attx/onto#CC0
* http://data.hulib.helsinki.fi/attx/onto#Unknown
