### ISSUE TITLE
Automatic provenance graph update

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/graphmanager#22]
#### Description

There is an endpoint in the GMapi to update the state of the provenance data graph with the data from the UV's database. Currently the responsibility to call that endpoint is outside of GMapi. 

We should come up with a way to schedule or trigger the same endpoint within the GMApi.  Simplest solution would be scheduled execution as planned earlier. 

#### DoD

Update to the docs and possibly some related implementation 

#### Testing
Testing depends on what we decide to do.

**Comment by blankdots** [comment]
Possible directions:
* https://afs.github.io/rdf-patch/
* https://www.w3.org/DesignIssues/Diff
* https://www.w3.org/TR/ldpatch/
* https://bertails.org/2014/09/20/why-ldpatch/
