### ISSUE TITLE
Extends the linkstrategy API to include more data from the individual strategy

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/graphmanager#24]
#### Description
Currently /linkstrategy return only "uri" field. This should be extended with at least "title" information so it could be more easily used in UI (see ATTX-project/workflow-component#43)

#### DoD
/linkstrategy return also "title" value for every strategy (and perhaps something else too).
#### Testing
Update integration tests.

**Comment by blankdots** [comment]
Result from linking strategies endpoint:
```
[
  {
    "title": "IDs based Linking Strategy",
    "uri": "http://data.hulib.helsinki.fi/attx/idstrategy1"
  },
  {
    "title": "IDs v2 based Linking Strategy",
    "uri": "http://data.hulib.helsinki.fi/attx/idstrategy2"
  }
]
```
Waiting for merge ... to deploy artifact. One can also test by creating a new pipeline or building locally.
Documentation update for the https://github.com/ATTX-project/project-management/wiki/Graph-Manager-API#linkstrategy-endpoint
