### ISSUE TITLE
Persistence GM API

### ISSUE THREAD

**Issue by blankdots** [ATTX-project/graphmanager#25]
#### Description
GM api DB needs to have persistence.
This will affect deployment and everything down the line.
#### DoD
Image and GM api are ready to have persistent data
#### Testing
Integration tests

**Comment by blankdots** [comment]
@joasilva and/or @jkesanie please review this see below where to find the jenkins task for the new artifact and this should not break https://github.com/ATTX-project/platform-deployment/issues/27
Running jenkins task with new version: `gm-api-volume`
Volume exposed by the container `/app/data`

Also reverting `gm-api` to command line utility instead of web-app due to some differences on permissions for `libexec/install` wheels for https://github.com/linkedin/pygradle/blob/master/pygradle-plugin/src/main/resources/templates/pex_non_cli_entrypoint.sh.template compared to https://github.com/linkedin/pygradle/blob/master/pygradle-plugin/src/main/resources/templates/pex_cli_entrypoint.py.template

As a result of this issue also a hotfix for wf-api has been done https://github.com/ATTX-project/workflow-component/commit/af4b75333081d184d73d006efbff1cb2a71f61b2

**Comment by joasilva** [comment]
How much data in GB is expected for GM-API "/app/data"?

**Comment by blankdots** [comment]
@joasilva maybe around 5GB or under 10GB

**Comment by jkesanie** [comment]
Tested as follows:
- start the platform
- add some data to the graph
- run /index three times
- restart gmapi container
- check the status of index processes with ids 1, 2 and 3. 
- verified that they were still where with the status "Done".

**Comment by blankdots** [comment]
This was tested in https://github.com/ATTX-project/platform-deployment/issues/28
