### ISSUE TITLE
Investigate/decide/plan asynchronous version of the GMapi

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/graphmanager#32]
#### DoD
Documentation

#### Testing
Peer-review

**Comment by jkesanie** [comment]
We have decided to move that burden from GM-api by introducing a MessageBroker to the stack.
Initial resources:
* https://github.com/ATTX-project/ATTX-project.github.io/blob/dev/attx_project/MessageBroker.md
* https://github.com/ATTX-project/ATTX-project.github.io/blob/dev/attx_project/images/messaging-request-response.svg
* https://github.com/ATTX-project/ATTX-project.github.io/blob/dev/attx_project/images/distribution-workflow-basic.svg
* https://github.com/ATTX-project/ATTX-project.github.io/blob/dev/attx_project/MessageBroker-ActiveMQ.md

**Comment by jkesanie** [comment]
@blankdots @joasilva comments?

**Comment by blankdots** [comment]
There needs to be some update to the role of GM-API to understand its functions and to see how it integrates with Message Broker and its endpoints - probably in the GM or GM-API documentation
Suggestion for followup where we describe the implementation and the messages and how to use ActiveMQ with our stack.
