### ISSUE TITLE
Document/implement dataset operations 

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/graphmanager#33]
#### Description
Graphmanager provides the following operations for datasets: 
* replace
* query
* add 
* retrieve

#### DoD
Documented Input and output of the operations. New version of the service.

#### Testing
Unit testing

**Comment by blankdots** [comment]
Documentation Started at: https://github.com/ATTX-project/ATTX-project.github.io/blob/dev/attx_project/Examples-Graph-Manager-Service.md

**Comment by blankdots** [comment]
79% unit tests, updated documentation and working implementation (TBD)
