### ISSUE TITLE
Document the v1 of the internal data model for UC1

### ISSUE THREAD

**Issue by blankdots** [ATTX-project/graphmanager#5]
#### Description
Document the v1 of the internal data model. Document also the 1st use case.
#### DoD
Wiki page updated/created for the documentation. See https://github.com/ATTX-project/workflow-component/issues/28
#### Testing
Peer Review

**Comment by jkesanie** [comment]
@blankdots  could you look at this? 
https://github.com/ATTX-project/project-management/wiki/UC1---Infrastructures-and-publications
